[alembic]
script_location = alembic
file_template = %%(rev)s_%%(slug)s
prepend_sys_path = .
timezone = UTC
sqlalchemy.url = sqlite:///./test_ai_research.db

[post_write_hooks]

[logging]
default_level = INFO
